add footer html and css
KonstantinBYC/team-project-g21 pull request #11
Opened 2023-04-07 22:19 UTC by Viktoria-Murko

2023-04-07 23:06 UTC, KonstantinBYC requested changes
Тут пару питань

2023-04-07 23:06 UTC, KonstantinBYC commented on src/partials/footer.html
> +        <ul class="footer-navigation-list">
Там еще полоска в ширину контейнера

2023-04-08 12:22 UTC, Viktoria-Murko commented on src/partials/footer.html
> +            <b class="footer-text"><span class="footer-accent-text">Chocolate</span> a delicious cure for a bad
+

2023-04-08 12:22 UTC, Viktoria-Murko commented on src/partials/footer.html
> +        <ul class="footer-navigation-list">
+

2023-04-08 13:24 UTC, KonstantinBYC approved these changes

2023-04-08 13:24 UTC, merged