feature-update
KonstantinBYC/team-project-g21 pull request #9
Opened 2023-04-07 20:46 UTC by Kamila0301

2023-04-07 21:05 UTC, KonstantinBYC requested changes
Прошу подивись)

2023-04-07 21:05 UTC, KonstantinBYC commented on src/partials/subscribe.html
> +</section>
все що нище прибрати

2023-04-07 21:05 UTC, KonstantinBYC commented on src/partials/subscribe.html
> +              <use href="../img/sprite.svg#icon-x-close"></use>
всі шляхи, як сказав ментор, ми задаємо відносно файлу index, тобто не ../img, а ./img

2023-04-07 21:05 UTC, KonstantinBYC commented on src/partials/subscribe.html
> +            <button type="submit" class="button-explore">Submit</button>
class="button-submit"?

2023-04-08 16:18 UTC, Kamila0301 commented on src/partials/subscribe.html
> +            <button type="submit" class="button-explore">Submit</button>
Інші ребята можуть так клас також назвати, тому персоналізувала)
Добре?

2023-04-08 21:20 UTC, KonstantinBYC approved these changes

2023-04-08 21:20 UTC, merged